# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

go:
  - 1.13.x

# Don't email me the results of the test runs.
notifications:
  email: false

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

# enable module cache
cache:
  directories:
    - $GOPATH/pkg/mod
    - ../keptn

jobs:
  include:
    - stage: tests
      os: linux
      script:
        - go test -v -race ./...  # Run all the tests with the race detector enabled

    - stage: Auto PR To Keptn
      # auto PR changes on the master branch (or tags) to keptn/keptn
      os: linux
      if: not type = pull_request and (branch = master or tag IS present)
      before_script:
        - git config --global user.email "florian.bacher@dynatrace.com"
        - git config --global user.name "Florian Bacher (kubernetes-utils Bot)"
        # figure out if this is a tag
        - |
          KUBERNETES_UTILS_TARGET=$TRAVIS_COMMIT
          if [[ $TRAVIS_TAG -ne "" ]]; then
            KUBERNETES_UTILS_TARGET=$TRAVIS_TAG
          fi
        - export DATE="$(date +'%Y%m%d.%H%M')"
      script:
        - cd ..
        # clone Keptn repo
        - git clone https://${GITHUB_TOKEN}@github.com/keptn/keptn.git || true
        - cd keptn
        # checkout master and ensure we are up2date
        - git checkout master
        - git pull || travis_terminate 1
        - export TARGET_BRANCH=patch/kubernetes_utils_${KUBERNETES_UTILS_TARGET}
        # delete existing branch just in case
        - git branch -D $TARGET_BRANCH &>/dev/null || true
        # create a new branch
        - git checkout -b $TARGET_BRANCH
        # update go modules in all directories that contain go.mod
        - |
          for file in *; do
             if [[ -f "$file/go.mod" ]]; then
                 echo "Checking if $file/go.mod contains kubernetes-utils"
                 grep "github.com/keptn/kubernetes-utils" $file/go.mod
                 if [[ $? -eq 0 ]]; then
                      echo "Yes, updating kubernetes-utils now..."
                      cd $file
                      go get "github.com/keptn/kubernetes-utils@$KUBERNETES_UTILS_TARGET"
                      cd ..
                 fi
             fi
          done
        - git status
        # add changes to a new commit
        - git add .
        - git commit -m "Update keptn/kubernetes-utils to $KUBERNETES_UTILS_TARGET" || travis_terminate 1
        - git push -f origin $TARGET_BRANCH || travis_terminate 1
        - |
          curl -XPOST -H "Authorization: token $GITHUB_TOKEN" -d "{\"title\":\"Auto-update kubernetes-utils to latest version\", \"base\":\"$BASE\", \"head\":\"$TARGET_BRANCH\", \"body\":\"**Boop beep I am a bot**\nThis is an automatically created PR to change [keptn/kubernetes-utils](https://github.com/keptn/kubernetes-utils) to version $KUBERNETES_UTILS_TARGET.\"}" https://api.github.com/repos/keptn/keptn/pulls || true